name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Create TWA project
        run: |
          bubblewrap init --manifest="https://thunderous-torrone-1fb7cc.netlify.app/manifest.json" --directory=twa --skipPwaValidation

      - name: Build APK/AAB
        run: |
          cd twa
          bubblewrap build

      - name: Upload APK/AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            twa/*.apk
            twa/*.aab
